function talk(){
var know = {
"what kind of website is this?" : "This website is all about astrology, specifically about zodiac signs ",
"What kind of website is this?" : "This website is all about astrology, specifically about zodiac signs ",

"this website is about?" : "This website is all about astrology, specifically about zodiac signs ",
"This website is about?" : "This website is all about astrology, specifically about zodiac signs ",

"tell me about this website" : "This website is all about astrology, specifically about zodiac signs ",
"Tell me about this website" : "This website is all about astrology, specifically about zodiac signs ",

"give me an insight about this website" : "This website is all about astrology, specifically about zodiac signs ",
"Give me an insight about this website" : "This website is all about astrology, specifically about zodiac signs ",

"what is aries?" : "(March 21 - April 19): In Greek mythology, Aries is associated with the story of the Golden Fleece. Aries represents the ram whose golden fleece was sought by Jason and the Argonauts. It symbolizes the quest for adventure, bravery, and the pursuit of greatness.",
"What is aries?" : "(March 21 - April 19): In Greek mythology, Aries is associated with the story of the Golden Fleece. Aries represents the ram whose golden fleece was sought by Jason and the Argonauts. It symbolizes the quest for adventure, bravery, and the pursuit of greatness.",
"What is Aries?" : "(March 21 - April 19): In Greek mythology, Aries is associated with the story of the Golden Fleece. Aries represents the ram whose golden fleece was sought by Jason and the Argonauts. It symbolizes the quest for adventure, bravery, and the pursuit of greatness.",

"what is taurus?" : "(April 20 - May 20): Taurus is associated with the story of the abduction of Europa. Zeus, the king of gods, transformed into a beautiful white bull to carry Europa, a Phoenician princess, across the sea to Crete. Taurus represents stability, sensuality, and the strength of the bull.",

"what is gemini?" : "(May 21 - June 20): Gemini is associated with the story of Castor and Pollux, also known as the Dioscuri. They were twin brothers in Greek mythology, one mortal and one immortal. After Castor's death, Pollux asked Zeus to let him share his immortality with his twin, symbolizing the duality and deep bond of the Gemini sign.",

"what is cancer?" : "(June 21 - July 22): Cancer is associated with the story of the Twelve Labors of Hercules. During one of his labors, Hercules had to defeat the nine-headed Hydra. However, each time Hercules cut off one of the Hydra's heads, two more would grow back. Finally, he managed to defeat it by cauterizing the stumps. The crab, represented by Cancer, was sent by Hera to distract Hercules during the battle. Hercules ultimately crushed the crab, but it was placed among the stars as a reward for its efforts.",

"what is leo?" : "(July 23 - August 22): Leo is associated with the story of the Nemean Lion, one of Hercules' twelve labors. The Nemean Lion was a vicious beast with an impenetrable hide that terrorized the land. Hercules was tasked with defeating it, and he succeeded by strangling the lion with his bare hands. The lion was then placed among the stars as the constellation Leo, representing strength, courage, and leadership.",

"what is virgo?" : "(August 23 - September 22): In Greek mythology, Virgo is associated with the story of Persephone and the harvest. Persephone, the daughter of Demeter, was abducted by Hades and taken to the Underworld. Demeter, the goddess of harvest and fertility, was devastated and caused the earth to become barren. Virgo represents the harvest season and the nurturing, analytical nature of Demeter.",

"what is libra?" : "(September 23 - October 22): Libra is associated with the story of Astraea, the Greek goddess of justice. According to the myth, Astraea was the last immortal to leave Earth as it became more corrupt. She ascended to the heavens and became the constellation Libra, representing fairness, balance, and the pursuit of justice.",

"what is scorpio?" : "(October 23 - November 21): Scorpio is associated with the story of Orion, a skilled hunter in Greek mythology. Orion was known for his great strength and his pursuit of the Pleiades, a group of seven sisters. Artemis, the goddess of the hunt, sent a scorpion to sting and kill Orion as punishment for his actions. Both Orion and the scorpion were placed in the sky as constellations, symbolizing transformation, passion, and intense emotions.",

"what is sagittarius?" : "(November 22 - December 21): Sagittarius is associated with the story of Chiron, the wise centaur in Greek mythology. Chiron was a skilled healer, archer, and teacher. He trained many heroes, including Achilles and Hercules. In the end, Chiron sacrificed his immortality to save Prometheus, and he was placed among the stars as the constellation Sagittarius, representing wisdom, adventure, and the pursuit of knowledge.",

"what is capricorn?" : "(December 22 - January 19): Capricorn is associated with the story of Pan, the Greek god of the wild and shepherds. According to the myth, Pan was being pursued by the monster Typhon and sought the help of Zeus. Zeus transformed Pan into a fish-tailed goat, known as Capricornus, allowing him to escape. Capricorn represents ambition, discipline, and the merging of the earthly and the spiritual.",

"what is aquarius?" : "(January 20 - February 18): Aquarius is associated with the story of Ganymede, a beautiful young man in Greek mythology. Zeus, captivated by Ganymede's beauty, transformed into an eagle and abducted him to serve as the cupbearer of the gods on Mount Olympus. Aquarius represents innovation, humanitarianism, and the pouring forth of knowledge.",

"what is pisces?" : "(February 19 - March 20): Pisces is associated with the story of Aphrodite and Eros. In Greek mythology, Aphrodite, the goddess of love, and her son Eros transformed into fish to escape the monster Typhon. They tied themselves together with a cord to ensure they would not lose each other. Pisces represents compassion, empathy, and the deep emotional connection between individuals.",

"personality of an aries" : "Aries is known for their energetic and assertive nature. They are confident, ambitious, and natural-born leaders. They have a competitive streak and love taking on challenges.",

"personality of an taurus" : "Taurus individuals are reliable, practical, and patient. They are known for their strong determination and stubbornness. They appreciate stability, material comforts, and have a love for the finer things in life.",

"personality of an gemini" : "Gemini is the sign of the twins, representing duality. Geminis are known for their versatility, curiosity, and wit. They are social butterflies and excellent communicators, but they can be indecisive at times.",

"personality of an cancer" : "Cancer individuals are sensitive, emotional, and nurturing. They are deeply loyal and protective of their loved ones. They have strong intuition and a strong attachment to home and family.",

"personality of an leo" : "Leos are confident, charismatic, and natural-born leaders. They have a strong presence and love being the center of attention. Leos are known for their generosity, creativity, and passion.",

"personality of an virgo" : "Virgos are analytical, practical, and detail-oriented. They have a strong work ethic and strive for perfection in everything they do. They are highly organized and value cleanliness and order.",

"personality of an libra" : "Libras are known for their diplomacy, charm, and desire for harmony. They are social butterflies and have a natural talent for bringing people together. They value fairness and seek balance in their relationships.",

"personality of an scorpio" : "Scorpios are passionate, intense, and mysterious. They have strong emotional depth and are highly intuitive. They are determined and fiercely loyal, but they can also be secretive and possessive.",

"personality of an sagittarius" : "Sagittarius individuals are adventurous, free-spirited, and optimistic. They have a love for travel and new experiences. They are known for their honesty, intellectual curiosity, and philosophical nature.",

"personality of an capricorn" : "Capricorns are responsible, disciplined, and ambitious individuals. They have a strong work ethic and are focused on achieving their goals. They value tradition and are highly reliable.",

"personality of an aquarius" : "Aquarius individuals are independent, progressive, and humanitarian. They have a unique and unconventional outlook on life. They are known for their intellectual prowess and love for social causes.",

"personality of an piscess" : "Pisces individuals are compassionate, imaginative, and intuitive. They have a deep connection with their emotions and the world around them. They are creative and have a strong artistic side.",

"What is a zodiac?" : "The term zodiac refers to an imaginary belt or circle in the sky that extends approximately eight degrees on either side of the ecliptic, which is the apparent path of the Sun across the celestial sphere throughout the year. It is divided into twelve equal parts, each representing one of the zodiac signs. The zodiac signs are based on the Earth's yearly journey around the Sun. As the Earth orbits the Sun, it appears that the Sun passes through each of the twelve zodiac signs, spending about a month in each sign. These signs are named after constellations that were present in the corresponding regions of the sky thousands of years ago, although they are no longer aligned with the current positions of the constellations due to a phenomenon called precession. Each zodiac sign is associated with specific personality traits, characteristics, and symbolism. Astrologers use the zodiac signs to interpret and analyze an individual's personality, relationships, and life events based on the position of celestial bodies at the time of their birth.",

"what is a zodiac?" : "The term zodiac refers to an imaginary belt or circle in the sky that extends approximately eight degrees on either side of the ecliptic, which is the apparent path of the Sun across the celestial sphere throughout the year. It is divided into twelve equal parts, each representing one of the zodiac signs. The zodiac signs are based on the Earth's yearly journey around the Sun. As the Earth orbits the Sun, it appears that the Sun passes through each of the twelve zodiac signs, spending about a month in each sign. These signs are named after constellations that were present in the corresponding regions of the sky thousands of years ago, although they are no longer aligned with the current positions of the constellations due to a phenomenon called precession. Each zodiac sign is associated with specific personality traits, characteristics, and symbolism. Astrologers use the zodiac signs to interpret and analyze an individual's personality, relationships, and life events based on the position of celestial bodies at the time of their birth.",

"what is zodiac" : "The term zodiac refers to an imaginary belt or circle in the sky that extends approximately eight degrees on either side of the ecliptic, which is the apparent path of the Sun across the celestial sphere throughout the year. It is divided into twelve equal parts, each representing one of the zodiac signs. The zodiac signs are based on the Earth's yearly journey around the Sun. As the Earth orbits the Sun, it appears that the Sun passes through each of the twelve zodiac signs, spending about a month in each sign. These signs are named after constellations that were present in the corresponding regions of the sky thousands of years ago, although they are no longer aligned with the current positions of the constellations due to a phenomenon called precession. Each zodiac sign is associated with specific personality traits, characteristics, and symbolism. Astrologers use the zodiac signs to interpret and analyze an individual's personality, relationships, and life events based on the position of celestial bodies at the time of their birth.",

"What is zodiac?" : "The term zodiac refers to an imaginary belt or circle in the sky that extends approximately eight degrees on either side of the ecliptic, which is the apparent path of the Sun across the celestial sphere throughout the year. It is divided into twelve equal parts, each representing one of the zodiac signs. The zodiac signs are based on the Earth's yearly journey around the Sun. As the Earth orbits the Sun, it appears that the Sun passes through each of the twelve zodiac signs, spending about a month in each sign. These signs are named after constellations that were present in the corresponding regions of the sky thousands of years ago, although they are no longer aligned with the current positions of the constellations due to a phenomenon called precession. Each zodiac sign is associated with specific personality traits, characteristics, and symbolism. Astrologers use the zodiac signs to interpret and analyze an individual's personality, relationships, and life events based on the position of celestial bodies at the time of their birth.",


//RANGE OF ARIES
"what zodiac is March 21" : "Aries ",
"what zodiac is March 22" : "Aries ",
"what zodiac is March 23" : "Aries ",
"what zodiac is March 24" : "Aries ",
"what zodiac is March 25" : "Aries ",
"what zodiac is March 26" : "Aries ",
"what zodiac is March 27" : "Aries ",
"what zodiac is March 28" : "Aries ",
"what zodiac is March 29" : "Aries ",
"what zodiac is March 30" : "Aries ",
"what zodiac is March 31" : "Aries ",
"what zodiac is April 1" : "Aries ",
"what zodiac is April 2" : "Aries ",
"what zodiac is April 3" : "Aries ",
"what zodiac is April 4" : "Aries ",
"what zodiac is April 5" : "Aries ",
"what zodiac is April 6" : "Aries ",
"what zodiac is April 7" : "Aries ",
"what zodiac is April 8" : "Aries ",
"what zodiac is April 9" : "Aries ",
"what zodiac is April 10" : "Aries ",
"what zodiac is April 11" : "Aries ",
"what zodiac is April 12" : "Aries ",
"what zodiac is April 13" : "Aries ",
"what zodiac is April 14" : "Aries ",
"what zodiac is April 15" : "Aries ",
"what zodiac is April 16" : "Aries ",
"what zodiac is April 17" : "Aries ",
"what zodiac is April 18" : "Aries ",
"what zodiac is April 19" : "Aries ",

//RANGE OF TAURUS
"what zodiac is April 20" : "Taurus ",
"what zodiac is April 21" : "Taurus ",
"what zodiac is April 22" : "Taurus ",
"what zodiac is April 23" : "Taurus ",
"what zodiac is April 24" : "Taurus ",
"what zodiac is April 25" : "Taurus ",
"what zodiac is April 26" : "Taurus ",
"what zodiac is April 27" : "Taurus ",
"what zodiac is April 28" : "Taurus ",
"what zodiac is April 29" : "Taurus ",
"what zodiac is April 30" : "Taurus ",
"what zodiac is May 1" : "Taurus ",
"what zodiac is May 2" : "Taurus ",
"what zodiac is May 3" : "Taurus ",
"what zodiac is May 4" : "Taurus ",
"what zodiac is May 5" : "Taurus ",
"what zodiac is May 6" : "Taurus ",
"what zodiac is May 7" : "Taurus ",
"what zodiac is May 8" : "Taurus ",
"what zodiac is May 9" : "Taurus ",
"what zodiac is May 10" : "Taurus ",
"what zodiac is May 11" : "Taurus ",
"what zodiac is May 12" : "Taurus ",
"what zodiac is May 13" : "Taurus ",
"what zodiac is May 14" : "Taurus ",
"what zodiac is May 15" : "Taurus ",
"what zodiac is May 16" : "Taurus ",
"what zodiac is May 17" : "Taurus ",
"what zodiac is May 18" : "Taurus ",
"what zodiac is May 19" : "Taurus ",
"what zodiac is May 20" : "Taurus ",


//RANGE OF GEMINI
"what zodiac is May 21" : "Gemini ",
"what zodiac is May 22" : "Gemini ",
"what zodiac is May 23" : "Gemini ",
"what zodiac is May 24" : "Gemini ",
"what zodiac is May 25" : "Gemini ",
"what zodiac is May 26" : "Gemini ",
"what zodiac is May 27" : "Gemini ",
"what zodiac is May 28" : "Gemini ",
"what zodiac is May 29" : "Gemini ",
"what zodiac is May 30" : "Gemini ",
"what zodiac is May 31" : "Gemini ",
"what zodiac is June 1" : "Gemini ",
"what zodiac is June 2" : "Gemini ",
"what zodiac is June 3" : "Gemini ",
"what zodiac is June 4" : "Gemini ",
"what zodiac is June 5" : "Gemini ",
"what zodiac is June 6" : "Gemini ",
"what zodiac is June 7" : "Gemini ",
"what zodiac is June 8" : "Gemini ",
"what zodiac is June 9" : "Gemini ",
"what zodiac is June 10" : "Gemini ",
"what zodiac is June 11" : "Gemini ",
"what zodiac is June 12" : "Gemini ",
"what zodiac is June 13" : "Gemini ",
"what zodiac is June 14" : "Gemini ",
"what zodiac is June 15" : "Gemini ",
"what zodiac is June 16" : "Gemini ",
"what zodiac is June 17" : "Gemini ",
"what zodiac is June 18" : "Gemini ",
"what zodiac is June 19" : "Gemini ",
"what zodiac is June 20" : "Gemini ",

//RANGE OF CANCER
"what zodiac is June 21" : "Cancer ",
"what zodiac is June 22" : "Cancer ",
"what zodiac is June 23" : "Cancer ",
"what zodiac is June 24" : "Cancer ",
"what zodiac is June 25" : "Cancer ",
"what zodiac is June 26" : "Cancer ",
"what zodiac is June 27" : "Cancer ",
"what zodiac is June 28" : "Cancer ",
"what zodiac is June 29" : "Cancer ",
"what zodiac is June 30" : "Cancer ",
"what zodiac is July 1" : "Cancer ",
"what zodiac is July 2" : "Cancer ",
"what zodiac is July 3" : "Cancer ",
"what zodiac is July 4" : "Cancer ",
"what zodiac is July 5" : "Cancer ",
"what zodiac is July 6" : "Cancer ",
"what zodiac is July 7" : "Cancer ",
"what zodiac is July 8" : "Cancer ",
"what zodiac is July 9" : "Cancer ",
"what zodiac is July 10" : "Cancer ",
"what zodiac is July 11" : "Cancer ",
"what zodiac is July 12" : "Cancer ",
"what zodiac is July 13" : "Cancer ",
"what zodiac is July 14" : "Cancer ",
"what zodiac is July 15" : "Cancer ",
"what zodiac is July 16" : "Cancer ",
"what zodiac is July 17" : "Cancer ",
"what zodiac is July 18" : "Cancer ",
"what zodiac is July 19" : "Cancer ",
"what zodiac is July 20" : "Cancer ",
"what zodiac is July 21" : "Cancer ",
"what zodiac is July 22" : "Cancer ",


//RANGE OF LEO
"what zodiac is July 23" : "Leo ",
"what zodiac is July 24" : "Leo ",
"what zodiac is July 25" : "Leo ",
"what zodiac is July 26" : "Leo ",
"what zodiac is July 27" : "Leo ",
"what zodiac is July 28" : "Leo ",
"what zodiac is July 29" : "Leo ",
"what zodiac is July 30" : "Leo ",
"what zodiac is July 31" : "Leo ",
"what zodiac is August 1" : "Leo ",
"what zodiac is August 2" : "Leo ",
"what zodiac is August 3" : "Leo ",
"what zodiac is August 4" : "Leo ",
"what zodiac is August 5" : "Leo ",
"what zodiac is August 6" : "Leo ",
"what zodiac is August 7" : "Leo ",
"what zodiac is August 8" : "Leo ",
"what zodiac is August 9" : "Leo ",
"what zodiac is August 10" : "Leo ",
"what zodiac is August 11" : "Leo ",
"what zodiac is August 12" : "Leo ",
"what zodiac is August 13" : "Leo ",
"what zodiac is August 14" : "Leo ",
"what zodiac is August 15" : "Leo ",
"what zodiac is August 16" : "Leo ",
"what zodiac is August 17" : "Leo ",
"what zodiac is August 18" : "Leo ",
"what zodiac is August 19" : "Leo ",
"what zodiac is August 20" : "Leo ",
"what zodiac is August 21" : "Leo ",
"what zodiac is August 22" : "Leo ",


//RANGE OF VIRGO
"what zodiac is August 23" : "Virgo ",
"what zodiac is August 24" : "Virgo ",
"what zodiac is August 25" : "Virgo ",
"what zodiac is August 26" : "Virgo ",
"what zodiac is August 27" : "Virgo ",
"what zodiac is August 28" : "Virgo ",
"what zodiac is August 29" : "Virgo ",
"what zodiac is August 30" : "Virgo ",
"what zodiac is August 31" : "Virgo ",
"what zodiac is September 1" : "Virgo ",
"what zodiac is September 2" : "Virgo ",
"what zodiac is September 3" : "Virgo ",
"what zodiac is September 4" : "Virgo ",
"what zodiac is September 5" : "Virgo ",
"what zodiac is September 6" : "Virgo ",
"what zodiac is September 7" : "Virgo ",
"what zodiac is September 8" : "Virgo ",
"what zodiac is September 9" : "Virgo ",
"what zodiac is September 10" : "Virgo ",
"what zodiac is September 11" : "Virgo ",
"what zodiac is September 12" : "Virgo ",
"what zodiac is September 13" : "Virgo ",
"what zodiac is September 14" : "Virgo ",
"what zodiac is September 15" : "Virgo ",
"what zodiac is September 16" : "Virgo ",
"what zodiac is September 17" : "Virgo ",
"what zodiac is September 18" : "Virgo ",
"what zodiac is September 19" : "Virgo ",
"what zodiac is September 20" : "Virgo ",
"what zodiac is September 21" : "Virgo ",
"what zodiac is September 22" : "Virgo ",


//RANGE OF LIBRA
"what zodiac is September 23" : "Libra ",
"what zodiac is September 24" : "Libra ",
"what zodiac is September 25" : "Libra ",
"what zodiac is September 26" : "Libra ",
"what zodiac is September 27" : "Libra ",
"what zodiac is September 28" : "Libra ",
"what zodiac is September 29" : "Libra ",
"what zodiac is September 30" : "Libra ",
"what zodiac is October 1" : "Libra ",
"what zodiac is October 2" : "Libra ",
"what zodiac is October 3" : "Libra ",
"what zodiac is October 4" : "Libra ",
"what zodiac is October 5" : "Libra ",
"what zodiac is October 6" : "Libra ",
"what zodiac is October 7" : "Libra ",
"what zodiac is October 8" : "Libra ",
"what zodiac is October 9" : "Libra ",
"what zodiac is October 10" : "Libra ",
"what zodiac is October 11" : "Libra ",
"what zodiac is October 12" : "Libra ",
"what zodiac is October 13" : "Libra ",
"what zodiac is October 14" : "Libra ",
"what zodiac is October 15" : "Libra ",
"what zodiac is October 16" : "Libra ",
"what zodiac is October 17" : "Libra ",
"what zodiac is October 18" : "Libra ",
"what zodiac is October 19" : "Libra ",
"what zodiac is October 20" : "Libra ",
"what zodiac is October 21" : "Libra ",
"what zodiac is October 22" : "Libra ",

//RANGE IN SCORPIO
"what zodiac is October 23" : "Scorpio ",
"what zodiac is October 24" : "Scorpio ",
"what zodiac is October 25" : "Scorpio ",
"what zodiac is October 26" : "Scorpio ",
"what zodiac is October 27" : "Scorpio ",
"what zodiac is October 28" : "Scorpio ",
"what zodiac is October 29" : "Scorpio ",
"what zodiac is October 30" : "Scorpio ",
"what zodiac is October 31" : "Scorpio ",
"what zodiac is November 1" : "Scorpio ",
"what zodiac is November 2" : "Scorpio ",
"what zodiac is November 3" : "Scorpio ",
"what zodiac is November 4" : "Scorpio ",
"what zodiac is November 5" : "Scorpio ",
"what zodiac is November 6" : "Scorpio ",
"what zodiac is November 7" : "Scorpio ",
"what zodiac is November 8" : "Scorpio ",
"what zodiac is November 9" : "Scorpio ",
"what zodiac is November 10" : "Scorpio ",
"what zodiac is November 11" : "Scorpio ",
"what zodiac is November 12" : "Scorpio ",
"what zodiac is November 13" : "Scorpio ",
"what zodiac is November 14" : "Scorpio ",
"what zodiac is November 15" : "Scorpio ",
"what zodiac is November 16" : "Scorpio ",
"what zodiac is November 17" : "Scorpio ",
"what zodiac is November 18" : "Scorpio ",
"what zodiac is November 19" : "Scorpio ",
"what zodiac is November 20" : "Scorpio ",
"what zodiac is November 21" : "Scorpio ",

//RANGE OF SAGITTARIUS
"what zodiac is November 22" : "Sagittarius ",
"what zodiac is November 23" : "Sagittarius ",
"what zodiac is November 24" : "Sagittarius ",
"what zodiac is November 25" : "Sagittarius ",
"what zodiac is November 26" : "Sagittarius ",
"what zodiac is November 27" : "Sagittarius",
"what zodiac is November 28" : "Sagittarius ",
"what zodiac is November 29" : "Sagittarius ",
"what zodiac is November 30" : "Sagittarius ",
"what zodiac is December 1" : "Sagittarius ",
"what zodiac is December 2" : "Sagittarius ",
"what zodiac is December 3" : "Sagittarius ",
"what zodiac is December 4" : "Sagittarius ",
"what zodiac is December 5" : "Sagittarius ",
"what zodiac is December 6" : "Sagittarius ",
"what zodiac is December 7" : "Sagittarius ",
"what zodiac is December 8" : "Sagittarius ",
"what zodiac is December 9" : "Sagittarius ",
"what zodiac is December 10" : "Sagittarius ",
"what zodiac is December 11" : "Sagittarius ",
"what zodiac is December 12" : "Sagittarius ",
"what zodiac is December 13" : "Sagittarius ",
"what zodiac is December 14" : "Sagittarius ",
"what zodiac is December 15" : "Sagittarius",
"what zodiac is December 16" : "Sagittarius ",
"what zodiac is December 17" : "Sagittarius ",
"what zodiac is December 18" : "Sagittarius ",
"what zodiac is December 19" : "Sagittarius ",
"what zodiac is December 20" : "Sagittarius ",
"what zodiac is December 21" : "Sagittarius ",


//RANGE OF CAPRICORN
"what zodiac is December 22" : "Capricorn ",
"what zodiac is December 23" : "Capricorn ",
"what zodiac is December 24" : "Capricorn ",
"what zodiac is December 25" : "Capricorn ",
"what zodiac is December 26" : "Capricorn ",
"what zodiac is December 27" : "Capricorn ",
"what zodiac is December 28" : "Capricorn ",
"what zodiac is December 29" : "Capricorn ",
"what zodiac is December 30" : "Capricorn ",
"what zodiac is December 31" : "Capricorn ",
"what zodiac is January 1" : "Capricorn ",
"what zodiac is January 2" : "Capricorn ",
"what zodiac is January 3" : "Capricorn ",
"what zodiac is January 4" : "Capricorn ",
"what zodiac is January 5" : "Capricorn ",
"what zodiac is January 6" : "Capricorn ",
"what zodiac is January 7" : "Capricorn ",
"what zodiac is January 8" : "Capricorn ",
"what zodiac is January 9" : "Capricorn ",
"what zodiac is January 10" : "Capricorn ",
"what zodiac is January 11" : "Capricorn ",
"what zodiac is January 12" : "Capricorn ",
"what zodiac is January 13" : "Capricorn ",
"what zodiac is January 14" : "Capricorn ",
"what zodiac is January 15" : "Capricorn ",
"what zodiac is January 16" : "Capricorn ",
"what zodiac is January 17" : "Capricorn ",
"what zodiac is January 18" : "Capricorn ",
"what zodiac is January 19" : "Capricorn ",


//RANGE OF AQUARIUS
"what zodiac is January 20" : "Aquarius ",
"what zodiac is January 21" : "Aquarius ",
"what zodiac is January 22" : "Aquarius ",
"what zodiac is January 23" : "Aquarius ",
"what zodiac is January 24" : "Aquarius ",
"what zodiac is January 25" : "Aquarius ",
"what zodiac is January 26" : "Aquarius ",
"what zodiac is January 27" : "Aquarius ",
"what zodiac is January 28" : "Aquarius ",
"what zodiac is January 29" : "Aquarius ",
"what zodiac is January 30" : "Aquarius ",
"what zodiac is January 31" : "Aquarius ",
"what zodiac is February 1" : "Aquarius ",
"what zodiac is February 2" : "Aquarius ",
"what zodiac is February 3" : "Aquarius ",
"what zodiac is February 4" : "Aquarius ",
"what zodiac is February 5" : "Aquarius ",
"what zodiac is February 6" : "Aquarius ",
"what zodiac is February 7" : "Aquarius ",
"what zodiac is February 8" : "Aquarius ",
"what zodiac is February 9" : "Aquarius ",
"what zodiac is February 10" : "Aquarius ",
"what zodiac is February 11" : "Aquarius ",
"what zodiac is February 12" : "Aquarius ",
"what zodiac is February 13" : "Aquarius ",
"what zodiac is February 14" : "Aquarius ",
"what zodiac is February 15" : "Aquarius ",
"what zodiac is February 16" : "Aquarius ",
"what zodiac is February 17" : "Aquarius ",
"what zodiac is February 18" : "Aquarius ",


//RANGE OF PISCES
"what zodiac is February 19" : "Pisces ",
"what zodiac is February 20" : "Pisces ",
"what zodiac is February 21" : "Pisces ",
"what zodiac is February 22" : "Pisces ",
"what zodiac is February 23" : "Pisces ",
"what zodiac is February 24" : "Pisces ",
"what zodiac is February 25" : "Pisces ",
"what zodiac is February 26" : "Pisces ",
"what zodiac is February 27" : "Pisces ",
"what zodiac is February 28" : "Pisces ",
"what zodiac is February 29" : "Pisces ",
"what zodiac is March 1" : "Pisces ",
"what zodiac is March 2" : "Pisces ",
"what zodiac is March 3" : "Pisces ",
"what zodiac is March 4" : "Pisces ",
"what zodiac is March 5" : "Pisces ",
"what zodiac is March 6" : "Pisces ",
"what zodiac is March 7" : "Pisces ",
"what zodiac is March 8" : "Pisces ",
"what zodiac is March 9" : "Pisces ",
"what zodiac is March 10" : "Pisces ",
"what zodiac is March 11" : "Pisces ",
"what zodiac is March 12" : "Pisces ",
"what zodiac is March 13" : "Pisces ",
"what zodiac is March 14" : "Pisces ",
"what zodiac is March 15" : "Pisces ",
"what zodiac is March 16" : "Pisces ",
"what zodiac is March 17" : "Pisces ",
"what zodiac is March 18" : "Pisces ",
"what zodiac is March 19" : "Pisces ",
"what zodiac is March 20" : "Pisces ",







"What are you?" : "a website",
"Bye" : "Okay! Will meet soon.."
};
var user = document.getElementById('userBox').value;
document.getElementById('chatLog').innerHTML = user + "<br>";
if (user in know) {
document.getElementById('chatLog').innerHTML = know[user] + "<br>";
}else{
document.getElementById('chatLog').innerHTML = "Sorry,I didn't understand <br>";
}
}